import { Document, Page, Text, View, StyleSheet, renderToBuffer, Link } from '@react-pdf/renderer';
import React from 'react';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: '2px solid #00E5FF',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#0A192F', // Navy
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 12,
        color: '#64748B',
    },
    intro: {
        fontSize: 11,
        marginBottom: 20,
        lineHeight: 1.5,
        color: '#334155',
    },
    table: {
        display: 'flex',
        width: 'auto',
        borderStyle: 'solid',
        borderWidth: 1,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: '#E2E8F0',
    },
    tableRow: {
        margin: 'auto',
        flexDirection: 'row',
    },
    tableColHeader: {
        width: '30%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: '#E2E8F0',
        backgroundColor: '#F1F5F9',
        padding: 5,
    },
    tableColHeaderWide: {
        width: '70%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: '#E2E8F0',
        backgroundColor: '#F1F5F9',
        padding: 5,
    },
    tableCol: {
        width: '30%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: '#E2E8F0',
        padding: 5,
    },
    tableColWide: {
        width: '70%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: '#E2E8F0',
        padding: 5,
    },
    textHeader: {
        fontSize: 10,
        fontWeight: 'bold',
    },
    textCell: {
        fontSize: 10,
    },
    link: {
        fontSize: 10,
        color: '#00E5FF',
        textDecoration: 'none',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        fontSize: 10,
        color: '#94A3B8',
        textAlign: 'center',
        borderTop: '1px solid #E2E8F0',
        paddingTop: 10,
    },
});

interface Broker {
    name: string;
    url?: string;
    notes?: string;
}

interface ChecklistProps {
    fullName: string;
    brokers: Broker[];
}

const ChecklistDocument = ({ fullName, brokers }: ChecklistProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>DataGhost Manual Removal Checklist</Text>
                <Text style={styles.subtitle}>Prepared for: {fullName}</Text>
            </View>

            <Text style={styles.intro}>
                We have automatically sent removal requests to all data brokers that accept email opt-outs (check your inbox for the CCs).
                {'\n\n'}
                However, the data brokers listed below do not accept automated emails and require you to fill out a web form. We've compiled the direct links for you below.
                {'\n\n'}
                Protocol: Click the link, fill the form, and check it off. Expect to spend about 15 minutes.
            </Text>

            <View style={styles.table}>
                <View style={styles.tableRow}>
                    <View style={styles.tableColHeader}>
                        <Text style={styles.textHeader}>Broker Name</Text>
                    </View>
                    <View style={styles.tableColHeaderWide}>
                        <Text style={styles.textHeader}>Direct Opt-Out Link</Text>
                    </View>
                </View>

                {brokers.map((broker, index) => (
                    <View style={styles.tableRow} key={index}>
                        <View style={styles.tableCol}>
                            <Text style={styles.textCell}>{broker.name}</Text>
                        </View>
                        <View style={styles.tableColWide}>
                            {broker.url ? (
                                <Link src={broker.url} style={styles.link}>
                                    {broker.url}
                                </Link>
                            ) : (
                                <Text style={styles.textCell}>No URL available</Text>
                            )}
                        </View>
                    </View>
                ))}
            </View>

            <View style={styles.footer}>
                <Text>Generated by DataGhost.me on {new Date().toLocaleDateString()}</Text>
            </View>
        </Page>
    </Document>
);

export async function generateChecklistPDF(fullName: string, brokers: Broker[]): Promise<Buffer> {
    return await renderToBuffer(<ChecklistDocument fullName={fullName} brokers={brokers} />);
}
